#define STATIC_PATH "/usr/lib/games/iwannaflycurses/"
#define VAR_PATH "/var/games/iwannaflycurses/"
#define GLOBAL_PATH "/etc/iwannaflycurses.d/"
#define SHARE_PATH "/usr/share/games/iwannaflycurses/"
#define DOC_PATH "/usr/share/doc/iwannaflycurses/"
#define GAMES_PATH "/usr/games/iwannaflycurses/"
#define DOT_PATH "~/.iwannaflycurses/"
